# Docker Compose pour Rock4you
# Déploiement complet avec base de données et volumes persistants

version: '3.8'

services:
  # Application principale (Frontend + Backend)
  rock4you-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"     # Frontend web
      - "3000:3000" # Backend API
    environment:
      - NODE_ENV=production
      - JWT_SECRET=${JWT_SECRET:-your-secret-key-change-me}
      - CORS_ORIGIN=${CORS_ORIGIN:-*}
      - DATABASE_PATH=/app/data/database.sqlite
    volumes:
      - rock4you_data:/app/backend/data
      - rock4you_assets:/app/assets
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Base de données SQLite (optionnel, pour backup/monitoring)
  db-backup:
    image: alpine:latest
    volumes:
      - rock4you_data:/data
    command: |
      sh -c "
        apk add --no-cache sqlite &&
        while true; do
          echo 'Backup DB à $(date)'
          sqlite3 /data/database.sqlite '.backup /data/backup-$(date +%Y%m%d-%H%M%S).sqlite'
          find /data -name 'backup-*.sqlite' -mtime +7 -delete
          sleep 86400
        done
      "
    restart: unless-stopped

volumes:
  rock4you_data:
    driver: local
  rock4you_assets:
    driver: local

networks:
  default:
    name: rock4you_network
