name = "rock4you-api"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "rock4you-api"

[env.staging]
name = "rock4you-api-staging"

[[d1_databases]]
binding = "DB"
database_name = "rock4you-db"
database_id = "a6dce45e-0f5f-40c6-87b5-d9845a9ffe74"

[vars]
JWT_SECRET = "DNbcvUCejZ56S4TVC1PEVeUWySbp9OBxBZyG85dgP2M="
CORS_ORIGIN = "*"
DEFAULT_FAVORITES_LIST_NAME = "Mes Favoris"

# Variables d'environnement pour le développement local
[env.development]
[env.development.vars]
JWT_SECRET = "dev-jwt-secret-change-in-production"
CORS_ORIGIN = "*"

[[env.development.d1_databases]]
binding = "DB"
database_name = "rock4you-db-dev"
database_id = "your-dev-database-id-here"