name = "rock4you-api"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "rock4you-api"

[env.staging]
name = "rock4you-api-staging"

[[d1_databases]]
binding = "DB"
database_name = "rock4you-db"
database_id = "your-database-id-here"

[vars]
JWT_SECRET = "your-jwt-secret-here"
CORS_ORIGIN = "https://your-app-domain.com"

# Variables d'environnement pour le développement local
[env.development]
[env.development.vars]
JWT_SECRET = "dev-jwt-secret-change-in-production"
CORS_ORIGIN = "*"

[[env.development.d1_databases]]
binding = "DB"
database_name = "rock4you-db-dev"
database_id = "your-dev-database-id-here"